[FIX] Status relaying on pipes
RezaRahemtola/42sh pull request #84
Opened 2022-05-28 22:24 UTC by Croos3r

# Description

Please provide a detailed description of what was done in this PR.
Precise the issue that you are resolving.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to an issue
- [x] I have linked this PR to a milestone
- [x] I have linked this PR to a project
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2022-05-28 22:27 UTC, EdenComp requested changes

2022-05-28 22:27 UTC, EdenComp commented on include/status.h
> +/*
par pitié change moi ça je veux bien split les headers mais pour une seule fonction non

2022-05-28 22:29 UTC, Croos3r commented on include/status.h
> +/*
Y'aura peut être d'autres truc à faire dedans et ça change pas grand chose en vrai

2022-05-28 22:46 UTC, RezaRahemtola approved these changes

2022-05-29 10:43 UTC, EdenComp approved these changes

2022-05-29 10:43 UTC, merged